site_name: iOS Club

site_url: https://tutorial.iosclub.tw

nav:
  - Home: index.md
  - 開始學習程式設計:
      - swift-learning/index.md
      - 指令:
          - swift-learning/command/index.md
          - 發出指令: swift-learning/command/1. issuing-commands.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.expand
  language: zh-TW
  font:
    text: "Noto Serif TC"
    code: "JetBrains Mono"
  palette:
    primary: light blue
  icon:
    logo: material/apple-ios

copyright: Copyright &copy; 2016 - 2023 FengChia University iOS Club

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
extra:
  social:
    - icon: material/web
      link: https://iosclub.tw
