site_name: iOS Club 教學網

site_url: https://tutorial.iosclub.tw

nav:
  - Home: index.md
  - 開始學習程式設計:
      - swift-learning/index.md
      - 指令:
          - swift-learning/1-commands/index.md
          - 發出指令: swift-learning/1-commands/1-issuing-commands.md
          - 加入新指令: swift-learning/1-commands/2-adding-a-new-command.md
          - 切換開關: swift-learning/1-commands/3-toggling-a-switch.md
          - 傳送門練習: swift-learning/1-commands/4-portal-practice.md
          - 尋找並修正程式錯誤: swift-learning/1-commands/5-finding-and-fixing-bugs.md
          - 除錯練習: swift-learning/1-commands/6-bug-squash-practice.md
          - 最短路線: swift-learning/1-commands/7-the-shortest-route.md
      - 函數:
          - swift-learning/2-functions/index.md
          - 組合新的動作: swift-learning/2-functions/1-composing-a-new-behavior.md
          - 建立新函數: swift-learning/2-functions/2-creating-a-new-function.md
          - 收集、切換、重複: swift-learning/2-functions/3-collect-toggle-repeat.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.expand
    - content.code.copy
  language: zh-TW
  font:
    text: "Noto Serif TC"
    code: "JetBrains Mono"
  palette:
    primary: light blue
  icon:
    logo: material/apple-ios

copyright: Copyright &copy; 2016 - 2023 FengChia University iOS Club

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
extra:
  social:
    - icon: material/web
      link: https://iosclub.tw
